name: website

on:
  push:
  schedule:
    - cron: '0 22 * * *'
permissions: 
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Gen dummy page
        env:
          currentTime: ${{ steps.time.outputs.starttime }}
          count: ${{ 0 }}
        run: |
          mkdir public
          # sudo mkdir -p /AdGuardSDNSFilter/
          # sudo pwd
          # sudo cd /home/runner/work/AdGuardSDNSFilter/
          sudo  echo > public/AdGuardSDNSFilter.txt 
          sudo wget https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt -O public/AdGuardSDNSFilter.txt 
          sudo chmod a+x public/AdGuardSDNSFilter.txt 
          sudo sed -i 's/^||/./;/^!.*/d;/^@@.*/d;s/\^$//;/^$/d;1i#·········' public/AdGuardSDNSFilter.txt
          currentTime=$(date "+%F %T") 
          count=$(awk '{print NR}' public/AdGuardSDNSFilter.txt |tail -n1)
          sudo sed -i -e "1i\#·········更新时间:${currentTime}·········数量:${count}条·········" public/AdGuardSDNSFilter.txt 
      -
        name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
